version: '3.1'

services:
  app-zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
        - "32181"

  app-kafka:
    image: confluentinc/cp-kafka:4.1.1
    depends_on:
      - app-zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=app-zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://app-kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1  # remove for >= 3 brokers
      - KAFKA_DELETE_TOPIC_ENABLE=true
    ports:
      - "9092"

  app-msb:
    image: msb:latest
    volumes:
       - $PWD/data:/home/jovyan/work/data:ro
    restart: always
    command: python bin/sendAlertStream.py app-kafka:9092 ztf-stream
    # deploy:
    #   restart_policy:
    #     condition: always
